version: "3"

services:
  ipt:
    container_name: ipt
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./iptdata:/usr/local/ipt/data
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xms128m -Xmx384m -XX:MaxMetaspaceSize=192m -XX:+UseSerialGC
    mem_limit: 640m
    memswap_limit: 1024m
